name: TotemStorage
main: me.JonathanHoffmann.TotemStorage.TotemStorage
author: Jonathan Hoffmann
version: ${plugin.version}
commands:
  storetotem:
    usage: /<command>
    permission: totemstorage.use
permissions:
  totemstorage.use:
    default: true

